/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiProblem,
  EquipmentCategoryItem,
  EquipmentCategoryRequest,
  ListEquipmentCategoriesParams
} from '../../model';

import { apiClient } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListEquipmentCategoriesUrl = (params?: ListEquipmentCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/equipment-categories?${stringifiedParams}` : `/api/v1/equipment-categories`
}

/**
 * @summary Lists the category tree as a flat list with each category's path.
 */
export const listEquipmentCategories = async (params?: ListEquipmentCategoriesParams, options?: Parameters<typeof apiClient>[1]): Promise<EquipmentCategoryItem[]> => {

  return apiClient<EquipmentCategoryItem[]>(getListEquipmentCategoriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEquipmentCategoriesQueryKey = (params?: ListEquipmentCategoriesParams,) => {
    return [
    `/api/v1/equipment-categories`, ...(params ? [params] : [])
    ] as const;
    }


export const getListEquipmentCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof listEquipmentCategories>>, TError = ApiProblem>(params?: ListEquipmentCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEquipmentCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEquipmentCategoriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEquipmentCategories>>> = ({ signal }) => listEquipmentCategories(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEquipmentCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEquipmentCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof listEquipmentCategories>>>
export type ListEquipmentCategoriesQueryError = ApiProblem


export function useListEquipmentCategories<TData = Awaited<ReturnType<typeof listEquipmentCategories>>, TError = ApiProblem>(
 params: undefined |  ListEquipmentCategoriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEquipmentCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEquipmentCategories>>,
          TError,
          Awaited<ReturnType<typeof listEquipmentCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEquipmentCategories<TData = Awaited<ReturnType<typeof listEquipmentCategories>>, TError = ApiProblem>(
 params?: ListEquipmentCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEquipmentCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEquipmentCategories>>,
          TError,
          Awaited<ReturnType<typeof listEquipmentCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEquipmentCategories<TData = Awaited<ReturnType<typeof listEquipmentCategories>>, TError = ApiProblem>(
 params?: ListEquipmentCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEquipmentCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lists the category tree as a flat list with each category's path.
 */

export function useListEquipmentCategories<TData = Awaited<ReturnType<typeof listEquipmentCategories>>, TError = ApiProblem>(
 params?: ListEquipmentCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEquipmentCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEquipmentCategoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateEquipmentCategoryUrl = () => {




  return `/api/v1/equipment-categories`
}

/**
 * @summary Adds a category under a parent or at the top.
 */
export const createEquipmentCategory = async (equipmentCategoryRequest: EquipmentCategoryRequest, options?: Parameters<typeof apiClient>[1]): Promise<EquipmentCategoryItem> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiClient<EquipmentCategoryItem>(getCreateEquipmentCategoryUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(equipmentCategoryRequest)
  }
);}





export const getCreateEquipmentCategoryMutationKey = () => ['createEquipmentCategory'] as const;

export const getCreateEquipmentCategoryMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEquipmentCategory>>, TError,CreateEquipmentCategoryMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createEquipmentCategory>>, TError,CreateEquipmentCategoryMutationVariables, TContext> => {

const mutationKey = getCreateEquipmentCategoryMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEquipmentCategory>>, CreateEquipmentCategoryMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createEquipmentCategory(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateEquipmentCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof createEquipmentCategory>>>
    export type CreateEquipmentCategoryMutationBody = EquipmentCategoryRequest
    export type CreateEquipmentCategoryMutationError = ApiProblem
    export type CreateEquipmentCategoryMutationVariables = {data: EquipmentCategoryRequest}

    /**
 * @summary Adds a category under a parent or at the top.
 */
export const useCreateEquipmentCategory = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEquipmentCategory>>, TError,CreateEquipmentCategoryMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEquipmentCategory>>,
        TError,
        CreateEquipmentCategoryMutationVariables,
        TContext
      > => {
      return useMutation(getCreateEquipmentCategoryMutationOptions(options), queryClient);
    }
    export const getEditEquipmentCategoryUrl = (categoryId: string,) => {




  return `/api/v1/equipment-categories/${categoryId}`
}

/**
 * @summary Renames a category or moves it under another parent.
 */
export const editEquipmentCategory = async (categoryId: string,
    equipmentCategoryRequest: EquipmentCategoryRequest, options?: Parameters<typeof apiClient>[1]): Promise<EquipmentCategoryItem> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiClient<EquipmentCategoryItem>(getEditEquipmentCategoryUrl(categoryId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(equipmentCategoryRequest)
  }
);}





export const getEditEquipmentCategoryMutationKey = () => ['editEquipmentCategory'] as const;

export const getEditEquipmentCategoryMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editEquipmentCategory>>, TError,EditEquipmentCategoryMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof editEquipmentCategory>>, TError,EditEquipmentCategoryMutationVariables, TContext> => {

const mutationKey = getEditEquipmentCategoryMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editEquipmentCategory>>, EditEquipmentCategoryMutationVariables> = (props) => {
          const {categoryId,data} = props ?? {};

          return  editEquipmentCategory(categoryId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditEquipmentCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof editEquipmentCategory>>>
    export type EditEquipmentCategoryMutationBody = EquipmentCategoryRequest
    export type EditEquipmentCategoryMutationError = ApiProblem
    export type EditEquipmentCategoryMutationVariables = {categoryId: string;data: EquipmentCategoryRequest}

    /**
 * @summary Renames a category or moves it under another parent.
 */
export const useEditEquipmentCategory = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editEquipmentCategory>>, TError,EditEquipmentCategoryMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editEquipmentCategory>>,
        TError,
        EditEquipmentCategoryMutationVariables,
        TContext
      > => {
      return useMutation(getEditEquipmentCategoryMutationOptions(options), queryClient);
    }
    export const getDeactivateEquipmentCategoryUrl = (categoryId: string,) => {




  return `/api/v1/equipment-categories/${categoryId}/deactivate`
}

/**
 * @summary Deactivates a category with nothing active under it.
 */
export const deactivateEquipmentCategory = async (categoryId: string, options?: Parameters<typeof apiClient>[1]): Promise<EquipmentCategoryItem> => {

  return apiClient<EquipmentCategoryItem>(getDeactivateEquipmentCategoryUrl(categoryId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDeactivateEquipmentCategoryMutationKey = () => ['deactivateEquipmentCategory'] as const;

export const getDeactivateEquipmentCategoryMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateEquipmentCategory>>, TError,DeactivateEquipmentCategoryMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deactivateEquipmentCategory>>, TError,DeactivateEquipmentCategoryMutationVariables, TContext> => {

const mutationKey = getDeactivateEquipmentCategoryMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivateEquipmentCategory>>, DeactivateEquipmentCategoryMutationVariables> = (props) => {
          const {categoryId} = props ?? {};

          return  deactivateEquipmentCategory(categoryId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivateEquipmentCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof deactivateEquipmentCategory>>>

    export type DeactivateEquipmentCategoryMutationError = ApiProblem
    export type DeactivateEquipmentCategoryMutationVariables = {categoryId: string}

    /**
 * @summary Deactivates a category with nothing active under it.
 */
export const useDeactivateEquipmentCategory = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateEquipmentCategory>>, TError,DeactivateEquipmentCategoryMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivateEquipmentCategory>>,
        TError,
        DeactivateEquipmentCategoryMutationVariables,
        TContext
      > => {
      return useMutation(getDeactivateEquipmentCategoryMutationOptions(options), queryClient);
    }
    export const getActivateEquipmentCategoryUrl = (categoryId: string,) => {




  return `/api/v1/equipment-categories/${categoryId}/activate`
}

/**
 * @summary Activates a deactivated category under an active parent.
 */
export const activateEquipmentCategory = async (categoryId: string, options?: Parameters<typeof apiClient>[1]): Promise<EquipmentCategoryItem> => {

  return apiClient<EquipmentCategoryItem>(getActivateEquipmentCategoryUrl(categoryId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getActivateEquipmentCategoryMutationKey = () => ['activateEquipmentCategory'] as const;

export const getActivateEquipmentCategoryMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateEquipmentCategory>>, TError,ActivateEquipmentCategoryMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof activateEquipmentCategory>>, TError,ActivateEquipmentCategoryMutationVariables, TContext> => {

const mutationKey = getActivateEquipmentCategoryMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateEquipmentCategory>>, ActivateEquipmentCategoryMutationVariables> = (props) => {
          const {categoryId} = props ?? {};

          return  activateEquipmentCategory(categoryId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateEquipmentCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof activateEquipmentCategory>>>

    export type ActivateEquipmentCategoryMutationError = ApiProblem
    export type ActivateEquipmentCategoryMutationVariables = {categoryId: string}

    /**
 * @summary Activates a deactivated category under an active parent.
 */
export const useActivateEquipmentCategory = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateEquipmentCategory>>, TError,ActivateEquipmentCategoryMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateEquipmentCategory>>,
        TError,
        ActivateEquipmentCategoryMutationVariables,
        TContext
      > => {
      return useMutation(getActivateEquipmentCategoryMutationOptions(options), queryClient);
    }
