/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiProblem,
  CreateThingRequest,
  RenameThingRequest,
  ThingCreated,
  ThingResponse
} from '../../model';

import { apiClient } from '../../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetThingUrl = (thingId: string,) => {




  return `/api/v1/things/${thingId}`
}

/**
 * @summary Gets a thing.
 */
export const getThing = async (thingId: string, options?: Parameters<typeof apiClient>[1]): Promise<ThingResponse> => {

  return apiClient<ThingResponse>(getGetThingUrl(thingId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetThingQueryKey = (thingId: string,) => {
    return [
    `/api/v1/things/${thingId}`
    ] as const;
    }


export const getGetThingQueryOptions = <TData = Awaited<ReturnType<typeof getThing>>, TError = ApiProblem>(thingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThing>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetThingQueryKey(thingId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getThing>>> = ({ signal }) => getThing(thingId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thingId !== null && thingId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getThing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetThingQueryResult = NonNullable<Awaited<ReturnType<typeof getThing>>>
export type GetThingQueryError = ApiProblem


export function useGetThing<TData = Awaited<ReturnType<typeof getThing>>, TError = ApiProblem>(
 thingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThing>>,
          TError,
          Awaited<ReturnType<typeof getThing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThing<TData = Awaited<ReturnType<typeof getThing>>, TError = ApiProblem>(
 thingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThing>>,
          TError,
          Awaited<ReturnType<typeof getThing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThing<TData = Awaited<ReturnType<typeof getThing>>, TError = ApiProblem>(
 thingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThing>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Gets a thing.
 */

export function useGetThing<TData = Awaited<ReturnType<typeof getThing>>, TError = ApiProblem>(
 thingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThing>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetThingQueryOptions(thingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getRenameThingUrl = (thingId: string,) => {




  return `/api/v1/things/${thingId}`
}

/**
 * @summary Renames a thing.
 */
export const renameThing = async (thingId: string,
    renameThingRequest: RenameThingRequest, options?: Parameters<typeof apiClient>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiClient<void>(getRenameThingUrl(thingId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(renameThingRequest)
  }
);}





export const getRenameThingMutationKey = () => ['renameThing'] as const;

export const getRenameThingMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameThing>>, TError,RenameThingMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof renameThing>>, TError,RenameThingMutationVariables, TContext> => {

const mutationKey = getRenameThingMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameThing>>, RenameThingMutationVariables> = (props) => {
          const {thingId,data} = props ?? {};

          return  renameThing(thingId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RenameThingMutationResult = NonNullable<Awaited<ReturnType<typeof renameThing>>>
    export type RenameThingMutationBody = RenameThingRequest
    export type RenameThingMutationError = ApiProblem
    export type RenameThingMutationVariables = {thingId: string;data: RenameThingRequest}

    /**
 * @summary Renames a thing.
 */
export const useRenameThing = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameThing>>, TError,RenameThingMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameThing>>,
        TError,
        RenameThingMutationVariables,
        TContext
      > => {
      return useMutation(getRenameThingMutationOptions(options), queryClient);
    }
    export const getCreateThingUrl = () => {




  return `/api/v1/things`
}

/**
 * @summary Creates a thing.
 */
export const createThing = async (createThingRequest: CreateThingRequest, options?: Parameters<typeof apiClient>[1]): Promise<ThingCreated> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiClient<ThingCreated>(getCreateThingUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createThingRequest)
  }
);}





export const getCreateThingMutationKey = () => ['createThing'] as const;

export const getCreateThingMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createThing>>, TError,CreateThingMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createThing>>, TError,CreateThingMutationVariables, TContext> => {

const mutationKey = getCreateThingMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createThing>>, CreateThingMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createThing(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateThingMutationResult = NonNullable<Awaited<ReturnType<typeof createThing>>>
    export type CreateThingMutationBody = CreateThingRequest
    export type CreateThingMutationError = ApiProblem
    export type CreateThingMutationVariables = {data: CreateThingRequest}

    /**
 * @summary Creates a thing.
 */
export const useCreateThing = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createThing>>, TError,CreateThingMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createThing>>,
        TError,
        CreateThingMutationVariables,
        TContext
      > => {
      return useMutation(getCreateThingMutationOptions(options), queryClient);
    }
