<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\FestOS.BuildingBlocks.Application\FestOS.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\FestOS.Modules.Riders.Contracts\FestOS.Modules.Riders.Contracts.csproj" />
    <ProjectReference Include="..\FestOS.Modules.Riders.Domain\FestOS.Modules.Riders.Domain.csproj" />
    <ProjectReference Include="..\..\Parties\FestOS.Modules.Parties.Contracts\FestOS.Modules.Parties.Contracts.csproj" />
    <ProjectReference Include="..\..\Catalog\FestOS.Modules.Catalog.Contracts\FestOS.Modules.Catalog.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FestOS.Modules.Riders.UnitTests" />
    <InternalsVisibleTo Include="FestOS.Modules.Riders.IntegrationTests" />
  </ItemGroup>
</Project>
