// <auto-generated />
using System;
using FestOS.Modules.Parties.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FestOS.Modules.Parties.Infrastructure.Migrations
{
    [DbContext(typeof(PartiesDbContext))]
    partial class PartiesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("parties")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FestOS.BuildingBlocks.Infrastructure.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_name");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("module");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("RootId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_id");

                    b.Property<string>("RootType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("root_type");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("ActorId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_actor_id_occurred_at");

                    b.HasIndex("OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_occurred_at_id");

                    b.HasIndex("RootId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_root_id_occurred_at_id");

                    b.ToTable("audit_entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_audit_entries_action_enum", "action IN ('created', 'deleted', 'statusChanged', 'updated')");
                        });
                });

            modelBuilder.Entity("FestOS.BuildingBlocks.Infrastructure.Idempotency.IdempotencyKey", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.HasKey("UserId", "Key")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_keys_created_at");

                    b.ToTable("idempotency_keys", "parties");
                });

            modelBuilder.Entity("FestOS.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "parties");
                });

            modelBuilder.Entity("FestOS.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderingKey")
                        .HasColumnType("uuid")
                        .HasColumnName("ordering_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Sequence"));

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("Sequence")
                        .HasDatabaseName("ix_outbox_messages_sequence")
                        .HasFilter("dispatched_at IS NULL AND failed_at IS NULL");

                    b.HasIndex("OrderingKey", "Sequence")
                        .HasDatabaseName("ix_outbox_messages_ordering_key_sequence")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable("outbox_messages", "parties");
                });

            modelBuilder.Entity("FestOS.Modules.Parties.Domain.Parties.ArtistRepresentation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_artist_representations");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_artist_representations_agency_id");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_artist_representations_artist_id");

                    b.ToTable("artist_representations", "parties");
                });

            modelBuilder.Entity("FestOS.Modules.Parties.Domain.Parties.ContactPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contact_points");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("ix_contact_points_party_id");

                    b.ToTable("contact_points", "parties", t =>
                        {
                            t.HasCheckConstraint("ck_contact_points_kind_enum", "kind IN ('address', 'email', 'phone')");
                        });
                });

            modelBuilder.Entity("FestOS.Modules.Parties.Domain.Parties.OrganizationContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_organization_contacts");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_contacts_organization_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_organization_contacts_person_id");

                    b.ToTable("organization_contacts", "parties");
                });

            modelBuilder.Entity("FestOS.Modules.Parties.Domain.Parties.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<Guid?>("DeactivatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivated_by");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<string>("Search")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.HasIndex("Roles")
                        .HasDatabaseName("ix_parties_roles");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Roles"), "gin");

                    b.HasIndex("Search")
                        .HasDatabaseName("ix_parties_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Search"), new[] { "gin_trgm_ops" });

                    b.ToTable("parties", "parties", t =>
                        {
                            t.HasCheckConstraint("ck_parties_kind_enum", "kind IN ('organization', 'person')");

                            t.HasCheckConstraint("ck_parties_kind_names", "(kind = 'person' AND first_name IS NOT NULL AND last_name IS NOT NULL AND legal_name IS NULL) OR (kind = 'organization' AND first_name IS NULL AND last_name IS NULL)");

                            t.HasCheckConstraint("ck_parties_roles_enum", "roles <@ ARRAY['agency', 'artist', 'contact', 'customer', 'supplier', 'venueOperator']::text[]");

                            t.HasCheckConstraint("ck_parties_roles_present", "cardinality(roles) > 0");
                        });
                });

            modelBuilder.Entity("FestOS.Modules.Parties.Domain.Parties.ArtistRepresentation", b =>
                {
                    b.HasOne("FestOS.Modules.Parties.Domain.Parties.Party", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_artist_representations_parties_agency_id");

                    b.HasOne("FestOS.Modules.Parties.Domain.Parties.Party", null)
                        .WithMany("Representations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_representations_parties_artist_id");
                });

            modelBuilder.Entity("FestOS.Modules.Parties.Domain.Parties.ContactPoint", b =>
                {
                    b.HasOne("FestOS.Modules.Parties.Domain.Parties.Party", null)
                        .WithMany("ContactPoints")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_points_parties_party_id");
                });

            modelBuilder.Entity("FestOS.Modules.Parties.Domain.Parties.OrganizationContact", b =>
                {
                    b.HasOne("FestOS.Modules.Parties.Domain.Parties.Party", null)
                        .WithMany("ContactPersons")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_contacts_parties_organization_id");

                    b.HasOne("FestOS.Modules.Parties.Domain.Parties.Party", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_contacts_parties_person_id");
                });

            modelBuilder.Entity("FestOS.Modules.Parties.Domain.Parties.Party", b =>
                {
                    b.Navigation("ContactPersons");

                    b.Navigation("ContactPoints");

                    b.Navigation("Representations");
                });
#pragma warning restore 612, 618
        }
    }
}
