<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\Audit\FestOS.Modules.Audit.Infrastructure\FestOS.Modules.Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\Identity\FestOS.Modules.Identity.Infrastructure\FestOS.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Testing\FestOS.Testing\FestOS.Testing.csproj" />
  </ItemGroup>
</Project>
