<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\FestOS.BuildingBlocks.Application\FestOS.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\FestOS.Modules.Inventory.Contracts\FestOS.Modules.Inventory.Contracts.csproj" />
    <ProjectReference Include="..\FestOS.Modules.Inventory.Domain\FestOS.Modules.Inventory.Domain.csproj" />
    <ProjectReference Include="..\FestOS.Modules.Inventory.IntegrationEvents\FestOS.Modules.Inventory.IntegrationEvents.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FestOS.Modules.Inventory.UnitTests" />
    <InternalsVisibleTo Include="FestOS.Modules.Inventory.IntegrationTests" />
  </ItemGroup>
</Project>
