/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


/**
 * @summary Signs in with an email and password.
 */
export const LoginBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
})

export const LoginResponse = zod.object({
  "id": zod.uuid(),
  "fullName": zod.string(),
  "email": zod.string(),
  "roles": zod.array(zod.enum(['systemAdministrator', 'bookingManager', 'technicalManager', 'warehouseManager', 'generalManager'])),
  "permissions": zod.array(zod.string()),
  "warehouseIds": zod.array(zod.uuid()),
  "mustChangePassword": zod.boolean()
})

/**
 * @summary Signs out.
 */
export const LogoutHeader = zod.object({
  "Idempotency-Key": zod.uuid().describe('A new UUID for each user action, and the same one when the action is retried (api §10).')
})

export const LogoutResponse = zod.void()

/**
 * @summary Gets the signed-in user.
 */
export const GetMeResponse = zod.object({
  "id": zod.uuid(),
  "fullName": zod.string(),
  "email": zod.string(),
  "roles": zod.array(zod.enum(['systemAdministrator', 'bookingManager', 'technicalManager', 'warehouseManager', 'generalManager'])),
  "permissions": zod.array(zod.string()),
  "warehouseIds": zod.array(zod.uuid()),
  "mustChangePassword": zod.boolean()
})

/**
 * @summary Sets a new password for the signed-in user; the user's other sessions end.
 */
export const ChangeMyPasswordHeader = zod.object({
  "Idempotency-Key": zod.uuid().describe('A new UUID for each user action, and the same one when the action is retried (api §10).')
})

export const ChangeMyPasswordBody = zod.object({
  "currentPassword": zod.string().nullable(),
  "newPassword": zod.string()
})

export const ChangeMyPasswordResponse = zod.object({
  "id": zod.uuid(),
  "fullName": zod.string(),
  "email": zod.string(),
  "roles": zod.array(zod.enum(['systemAdministrator', 'bookingManager', 'technicalManager', 'warehouseManager', 'generalManager'])),
  "permissions": zod.array(zod.string()),
  "warehouseIds": zod.array(zod.uuid()),
  "mustChangePassword": zod.boolean()
})

/**
 * @summary Lists the users, searched and filtered, one page at a time.
 */
export const ListUsersQueryParams = zod.object({
  "q": zod.string().optional(),
  "role": zod.enum(['systemAdministrator', 'bookingManager', 'technicalManager', 'warehouseManager', 'generalManager']).optional(),
  "status": zod.enum(['active', 'inactive', 'all']).optional(),
  "sort": zod.string().optional(),
  "page": zod.int().optional(),
  "pageSize": zod.int().optional()
})

export const ListUsersResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "fullName": zod.string(),
  "email": zod.string(),
  "roles": zod.array(zod.enum(['systemAdministrator', 'bookingManager', 'technicalManager', 'warehouseManager', 'generalManager'])),
  "isActive": zod.boolean(),
  "lockedUntil": zod.iso.datetime({"offset":true}).nullable()
})),
  "page": zod.int(),
  "pageSize": zod.int(),
  "totalCount": zod.int()
})

/**
 * @summary Gets a user.
 */
export const GetUserParams = zod.object({
  "userId": zod.uuid()
})

export const GetUserResponse = zod.object({
  "id": zod.uuid(),
  "fullName": zod.string(),
  "email": zod.string(),
  "roles": zod.array(zod.enum(['systemAdministrator', 'bookingManager', 'technicalManager', 'warehouseManager', 'generalManager'])),
  "warehouseIds": zod.array(zod.uuid()),
  "mustChangePassword": zod.boolean(),
  "lockedUntil": zod.iso.datetime({"offset":true}).nullable(),
  "deactivatedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "version": zod.int()
})

