/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { ApiProblemErrorsItem } from './apiProblemErrorsItem';
import type { ApiProblemParams } from './apiProblemParams';

export interface ApiProblem {
  type: string;
  title: string;
  status: number;
  detail: string;
  instance: string;
  code: string;
  traceId: string;
  params?: ApiProblemParams;
  errors?: ApiProblemErrorsItem[];
}
