/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export type AuditAction = typeof AuditAction[keyof typeof AuditAction];


export const AuditAction = {
  created: 'created',
  updated: 'updated',
  deleted: 'deleted',
  statusChanged: 'statusChanged',
} as const;
