/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { AuditAction } from './auditAction';
import type { JsonElement } from './jsonElement';

export interface AuditEntryItem {
  id: string;
  occurredAt: string;
  actorId: string;
  actorName: string;
  module: string;
  entityType: string;
  entityId: string;
  rootType: string;
  rootId: string;
  action: AuditAction;
  changes: JsonElement;
  /** @nullable */
  traceId: string | null;
}
