/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export type CategoryStatusFilter = typeof CategoryStatusFilter[keyof typeof CategoryStatusFilter];


export const CategoryStatusFilter = {
  active: 'active',
  inactive: 'inactive',
  all: 'all',
} as const;
