/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export interface ChangeMyPasswordRequest {
  /** @nullable */
  currentPassword: string | null;
  newPassword: string;
}
