/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export type ContactPointKind = typeof ContactPointKind[keyof typeof ContactPointKind];


export const ContactPointKind = {
  phone: 'phone',
  email: 'email',
  address: 'address',
} as const;
