/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { ContactPointId } from './contactPointId';
import type { ContactPointKind } from './contactPointKind';

export interface ContactPointItem {
  id: ContactPointId;
  kind: ContactPointKind;
  value: string;
  /** @nullable */
  label: string | null;
  isPrimary: boolean;
}
