/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { RiderLineRequest } from './riderLineRequest';

export interface CreateRiderVersionRequest {
  lines: RiderLineRequest[];
  /** @nullable */
  note?: string | null;
}
