/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { PartyId } from './partyId';

export interface EmployerItem {
  organizationId: PartyId;
  name: string;
  /** @nullable */
  title: string | null;
  isActive: boolean;
}
