/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { TrackingType } from './trackingType';

export interface EquipmentModelRequest {
  brand: string;
  name: string;
  categoryId: string;
  trackingType: TrackingType;
  /** @nullable */
  weightKilograms?: string | null;
  /** @nullable */
  powerWatts?: number | null;
  /** @nullable */
  transportVolumeCubicMeters?: string | null;
}
