/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export interface KitLineRequest {
  quantity: number;
  /** @nullable */
  modelId?: string | null;
  /** @nullable */
  subKitId?: string | null;
}
