/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { KitId } from './kitId';
import type { KitTotals } from './kitTotals';

export interface KitListItem {
  id: KitId;
  name: string;
  lineCount: number;
  totals: KitTotals;
  isActive: boolean;
  version: number;
}
