/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { KitId } from './kitId';

export interface KitReference {
  id: KitId;
  name: string;
  isActive: boolean;
}
