/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export type ListAuditEntriesParams = {
actorId?: string;
from?: string;
to?: string;
module?: string;
entityType?: string;
entityId?: string;
after?: string;
limit?: number;
};
