/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { KitStatusFilter } from './kitStatusFilter';

export type ListKitsParams = {
q?: string;
status?: KitStatusFilter;
page?: number;
pageSize?: number;
};
