/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { ProductionStatusFilter } from './productionStatusFilter';

export type ListProductionsParams = {
artistId?: string;
q?: string;
status?: ProductionStatusFilter;
sort?: string;
page?: number;
pageSize?: number;
};
