/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { WarehouseStatusFilter } from './warehouseStatusFilter';

export type ListWarehousesParams = {
q?: string;
status?: WarehouseStatusFilter;
sort?: string;
page?: number;
pageSize?: number;
};
