/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { VenueStatusFilter } from './venueStatusFilter';

export type ListVenuesParams = {
q?: string;
city?: string;
status?: VenueStatusFilter;
sort?: string;
page?: number;
pageSize?: number;
};
