/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export type ModelStatusFilter = typeof ModelStatusFilter[keyof typeof ModelStatusFilter];


export const ModelStatusFilter = {
  active: 'active',
  inactive: 'inactive',
  all: 'all',
} as const;
