/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { ProductionListItem } from './productionListItem';

export interface PagedResultOfProductionListItem {
  items: ProductionListItem[];
  page: number;
  pageSize: number;
  totalCount: number;
}
