/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { EquipmentModelListItem } from './equipmentModelListItem';

export interface PagedResultOfEquipmentModelListItem {
  items: EquipmentModelListItem[];
  page: number;
  pageSize: number;
  totalCount: number;
}
