/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { KitListItem } from './kitListItem';

export interface PagedResultOfKitListItem {
  items: KitListItem[];
  page: number;
  pageSize: number;
  totalCount: number;
}
