/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { UserListItem } from './userListItem';

export interface PagedResultOfUserListItem {
  items: UserListItem[];
  page: number;
  pageSize: number;
  totalCount: number;
}
