/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { ContactPointItem } from './contactPointItem';
import type { PartyId } from './partyId';
import type { PartyKind } from './partyKind';
import type { PartyRole } from './partyRole';

export interface PartyDetails {
  id: PartyId;
  kind: PartyKind;
  name: string;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  legalName: string | null;
  roles: PartyRole[];
  contactPoints: ContactPointItem[];
  /** @nullable */
  deactivatedAt: string | null;
  createdAt: string;
  updatedAt: string;
  version: number;
}
