/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { ContactPersonItem } from './contactPersonItem';
import type { ContactPointItem } from './contactPointItem';
import type { EmployerItem } from './employerItem';
import type { PartyId } from './partyId';
import type { PartyKind } from './partyKind';
import type { PartyRole } from './partyRole';
import type { RepresentationItem } from './representationItem';
import type { RepresentedArtistItem } from './representedArtistItem';

export interface PartyDetails {
  id: PartyId;
  kind: PartyKind;
  name: string;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  legalName: string | null;
  roles: PartyRole[];
  contactPoints: ContactPointItem[];
  contactPersons: ContactPersonItem[];
  representations: RepresentationItem[];
  representedArtists: RepresentedArtistItem[];
  employers: EmployerItem[];
  /** @nullable */
  deactivatedAt: string | null;
  createdAt: string;
  updatedAt: string;
  version: number;
}
