/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { ContactPointRequest } from './contactPointRequest';
import type { PartyKind } from './partyKind';
import type { PartyRole } from './partyRole';

export interface PartyRequest {
  name: string;
  roles: PartyRole[];
  contactPoints: ContactPointRequest[];
  kind?: null | PartyKind;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  legalName?: string | null;
}
