/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { Role } from './role';

export interface PermissionGrant {
  code: string;
  roles: Role[];
}
