/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export interface RepresentationDescriptionRequest {
  /** @nullable */
  description?: string | null;
}
