/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { ArtistRepresentationId } from './artistRepresentationId';
import type { PartyId } from './partyId';

export interface RepresentationItem {
  id: ArtistRepresentationId;
  agencyId: PartyId;
  agencyName: string;
  /** @nullable */
  description: string | null;
  isActive: boolean;
}
