/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { RiderId } from './riderId';
import type { RiderLineItem } from './riderLineItem';
import type { RiderVersionId } from './riderVersionId';

export interface RiderVersionDetails {
  id: RiderVersionId;
  riderId: RiderId;
  number: number;
  /** @nullable */
  note: string | null;
  createdAt: string;
  createdByName: string;
  lines: RiderLineItem[];
}
