/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { RiderEquivalentItem } from './riderEquivalentItem';
import type { RiderLineFlexibility } from './riderLineFlexibility';
import type { RiderLineId } from './riderLineId';

export interface RiderLineItem {
  id: RiderLineId;
  lineKey: string;
  /** @nullable */
  modelId: string | null;
  /** @nullable */
  categoryId: string | null;
  name: string;
  categoryPath: string[];
  isTargetActive: boolean;
  quantity: number;
  flexibility: null | RiderLineFlexibility;
  equivalents: RiderEquivalentItem[];
  /** @nullable */
  note: string | null;
}
