/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { RiderLineFlexibility } from './riderLineFlexibility';

export interface RiderLineRequest {
  quantity: number;
  /** @nullable */
  lineKey?: string | null;
  /** @nullable */
  modelId?: string | null;
  /** @nullable */
  categoryId?: string | null;
  flexibility?: null | RiderLineFlexibility;
  /** @nullable */
  equivalentModelIds?: string[] | null;
  /** @nullable */
  note?: string | null;
}
