/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { RiderVersionListItem } from './riderVersionListItem';

export interface RiderVersionList {
  versions: RiderVersionListItem[];
  version: number;
}
