/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { RiderVersionId } from './riderVersionId';

export interface RiderVersionListItem {
  id: RiderVersionId;
  number: number;
  /** @nullable */
  note: string | null;
  createdAt: string;
  createdByName: string;
  lineCount: number;
}
