/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { ModulePermissions } from './modulePermissions';
import type { Role } from './role';

export interface RoleMatrix {
  roles: Role[];
  modules: ModulePermissions[];
}
