/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { Role } from './role';
import type { UserId } from './userId';

export interface SignedInUserDetails {
  id: UserId;
  fullName: string;
  email: string;
  roles: Role[];
  permissions: string[];
  warehouseIds: string[];
  mustChangePassword: boolean;
}
