/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export type TrackingType = typeof TrackingType[keyof typeof TrackingType];


export const TrackingType = {
  serialized: 'serialized',
  bulk: 'bulk',
} as const;
