/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { VenueEquipmentUnavailabilityId } from './venueEquipmentUnavailabilityId';

export interface UnavailabilityItem {
  id: VenueEquipmentUnavailabilityId;
  periodStart: string;
  periodEnd: string;
  quantity: number;
  reason: string;
}
