/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { UserDetails } from './userDetails';

export interface UserPasswordReset {
  user: UserDetails;
  temporaryPassword: string;
}
