/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { VenueId } from './venueId';

export interface VenueListItem {
  id: VenueId;
  name: string;
  city: string;
  capacity: number;
  /** @nullable */
  operatorPartyId: string | null;
  /** @nullable */
  operatorName: string | null;
  isActive: boolean;
  version: number;
}
