/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { VenueId } from './venueId';

export interface VenueDetails {
  id: VenueId;
  name: string;
  city: string;
  address: string;
  /** @nullable */
  operatorPartyId: string | null;
  /** @nullable */
  operatorName: string | null;
  isOperatorActive: boolean;
  capacity: number;
  /** @nullable */
  stageWidthMeters: string | null;
  /** @nullable */
  stageDepthMeters: string | null;
  /** @nullable */
  stageHeightMeters: string | null;
  /** @nullable */
  loadingDock: string | null;
  /** @nullable */
  powerCapacityAmperes: string | null;
  /** @nullable */
  curfew: string | null;
  timeZone: string;
  /** @nullable */
  deactivatedAt: string | null;
  createdAt: string;
  updatedAt: string;
  version: number;
}
