/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export type WarehouseStatusFilter = typeof WarehouseStatusFilter[keyof typeof WarehouseStatusFilter];


export const WarehouseStatusFilter = {
  active: 'active',
  inactive: 'inactive',
  all: 'all',
} as const;
