/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { WarehouseId } from './warehouseId';

export interface WarehouseListItem {
  id: WarehouseId;
  name: string;
  city: string;
  address: string;
  isActive: boolean;
  version: number;
}
