/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


/**
 * @summary Gets a thing.
 */
export const GetThingParams = zod.object({
  "thingId": zod.uuid()
})

export const getThingResponseFeeCurrencyRegExp = new RegExp('^[A-Z]{3}$');


export const GetThingResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "note": zod.string().nullable(),
  "price": zod.string(),
  "discount": zod.string().nullable(),
  "status": zod.enum(['draft', 'inUse']),
  "previousStatus": zod.union([zod.null(),zod.enum(['draft', 'inUse'])]),
  "buffer": zod.int().describe('Whole minutes.'),
  "fee": zod.object({
  "amount": zod.string().optional(),
  "currency": zod.string().regex(getThingResponseFeeCurrencyRegExp).optional()
}),
  "tags": zod.array(zod.string()).nullable(),
  "part": zod.union([zod.null(),zod.object({
  "label": zod.string()
})]),
  "version": zod.int()
})

/**
 * @summary Renames a thing.
 */
export const RenameThingParams = zod.object({
  "thingId": zod.uuid()
})

export const RenameThingHeader = zod.object({
  "If-Match": zod.string().describe('The version the change is based on, as a strong entity tag, e.g. "7" (api §9).'),
  "Idempotency-Key": zod.uuid().describe('A new UUID for each user action, and the same one when the action is retried (api §10).')
})

export const RenameThingBody = zod.object({
  "name": zod.string()
})

export const RenameThingResponse = zod.void()

/**
 * @summary Creates a thing.
 */
export const CreateThingHeader = zod.object({
  "Idempotency-Key": zod.uuid().describe('A new UUID for each user action, and the same one when the action is retried (api §10).')
})

export const CreateThingBody = zod.object({
  "name": zod.string(),
  "price": zod.string(),
  "status": zod.enum(['draft', 'inUse'])
})

export const CreateThingResponse = zod.object({
  "id": zod.uuid()
})

