<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\FestOS.BuildingBlocks.Domain\FestOS.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\FestOS.BuildingBlocks.Application\FestOS.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\FestOS.BuildingBlocks.Infrastructure\FestOS.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\FestOS.BuildingBlocks.Contracts\FestOS.BuildingBlocks.Contracts.csproj" />
  </ItemGroup>
</Project>
