/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import type { Currency } from './currency';

export interface Money {
  amount?: string;
  currency?: Currency;
}
