/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */

export type ThingStatus = typeof ThingStatus[keyof typeof ThingStatus];


export const ThingStatus = {
  draft: 'draft',
  inUse: 'inUse',
} as const;
