/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminWarehousesRouteImport } from './routes/_app/admin/warehouses'
import { Route as AppArtistsIndexRouteImport } from './routes/_app/artists/index'
import { Route as AppCatalogCategoriesRouteImport } from './routes/_app/catalog/categories'
import { Route as AppPartiesIndexRouteImport } from './routes/_app/parties/index'
import { Route as AppVenuesIndexRouteImport } from './routes/_app/venues/index'
import { Route as AppArtistsPartyIdIndexRouteImport } from './routes/_app/artists/$partyId/index'
import { Route as AppArtistsPartyIdHistoryRouteImport } from './routes/_app/artists/$partyId/history'
import { Route as AppCatalogKitsIndexRouteImport } from './routes/_app/catalog/kits/index'
import { Route as AppCatalogModelsIndexRouteImport } from './routes/_app/catalog/models/index'
import { Route as AppCatalogModelsNewRouteImport } from './routes/_app/catalog/models/new'
import { Route as AppPartiesPartyIdIndexRouteImport } from './routes/_app/parties/$partyId/index'
import { Route as AppPartiesPartyIdHistoryRouteImport } from './routes/_app/parties/$partyId/history'
import { Route as AppProductionsProductionIdIndexRouteImport } from './routes/_app/productions/$productionId/index'
import { Route as AppProductionsProductionIdHistoryRouteImport } from './routes/_app/productions/$productionId/history'
import { Route as AppVenuesVenueIdIndexRouteImport } from './routes/_app/venues/$venueId/index'
import { Route as AppVenuesVenueIdEquipmentRouteImport } from './routes/_app/venues/$venueId/equipment'
import { Route as AppVenuesVenueIdHistoryRouteImport } from './routes/_app/venues/$venueId/history'
import { Route as AppCatalogKitsKitIdIndexRouteImport } from './routes/_app/catalog/kits/$kitId/index'
import { Route as AppCatalogKitsKitIdHistoryRouteImport } from './routes/_app/catalog/kits/$kitId/history'
import { Route as AppCatalogModelsModelIdIndexRouteImport } from './routes/_app/catalog/models/$modelId/index'
import { Route as AppCatalogModelsModelIdEditRouteImport } from './routes/_app/catalog/models/$modelId/edit'
import { Route as AppCatalogModelsModelIdHistoryRouteImport } from './routes/_app/catalog/models/$modelId/history'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminWarehousesRoute = AppAdminWarehousesRouteImport.update({
  id: '/admin/warehouses',
  path: '/admin/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppArtistsIndexRoute = AppArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogCategoriesRoute = AppCatalogCategoriesRouteImport.update({
  id: '/catalog/categories',
  path: '/catalog/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesIndexRoute = AppPartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => AppRoute,
} as any)
const AppVenuesIndexRoute = AppVenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => AppRoute,
} as any)
const AppArtistsPartyIdIndexRoute = AppArtistsPartyIdIndexRouteImport.update({
  id: '/artists/$partyId/',
  path: '/artists/$partyId/',
  getParentRoute: () => AppRoute,
} as any)
const AppArtistsPartyIdHistoryRoute =
  AppArtistsPartyIdHistoryRouteImport.update({
    id: '/artists/$partyId/history',
    path: '/artists/$partyId/history',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogKitsIndexRoute = AppCatalogKitsIndexRouteImport.update({
  id: '/catalog/kits/',
  path: '/catalog/kits/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogModelsIndexRoute = AppCatalogModelsIndexRouteImport.update({
  id: '/catalog/models/',
  path: '/catalog/models/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogModelsNewRoute = AppCatalogModelsNewRouteImport.update({
  id: '/catalog/models/new',
  path: '/catalog/models/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesPartyIdIndexRoute = AppPartiesPartyIdIndexRouteImport.update({
  id: '/parties/$partyId/',
  path: '/parties/$partyId/',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesPartyIdHistoryRoute =
  AppPartiesPartyIdHistoryRouteImport.update({
    id: '/parties/$partyId/history',
    path: '/parties/$partyId/history',
    getParentRoute: () => AppRoute,
  } as any)
const AppProductionsProductionIdIndexRoute =
  AppProductionsProductionIdIndexRouteImport.update({
    id: '/productions/$productionId/',
    path: '/productions/$productionId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProductionsProductionIdHistoryRoute =
  AppProductionsProductionIdHistoryRouteImport.update({
    id: '/productions/$productionId/history',
    path: '/productions/$productionId/history',
    getParentRoute: () => AppRoute,
  } as any)
const AppVenuesVenueIdIndexRoute = AppVenuesVenueIdIndexRouteImport.update({
  id: '/venues/$venueId/',
  path: '/venues/$venueId/',
  getParentRoute: () => AppRoute,
} as any)
const AppVenuesVenueIdEquipmentRoute =
  AppVenuesVenueIdEquipmentRouteImport.update({
    id: '/venues/$venueId/equipment',
    path: '/venues/$venueId/equipment',
    getParentRoute: () => AppRoute,
  } as any)
const AppVenuesVenueIdHistoryRoute = AppVenuesVenueIdHistoryRouteImport.update({
  id: '/venues/$venueId/history',
  path: '/venues/$venueId/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogKitsKitIdIndexRoute =
  AppCatalogKitsKitIdIndexRouteImport.update({
    id: '/catalog/kits/$kitId/',
    path: '/catalog/kits/$kitId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogKitsKitIdHistoryRoute =
  AppCatalogKitsKitIdHistoryRouteImport.update({
    id: '/catalog/kits/$kitId/history',
    path: '/catalog/kits/$kitId/history',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogModelsModelIdIndexRoute =
  AppCatalogModelsModelIdIndexRouteImport.update({
    id: '/catalog/models/$modelId/',
    path: '/catalog/models/$modelId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogModelsModelIdEditRoute =
  AppCatalogModelsModelIdEditRouteImport.update({
    id: '/catalog/models/$modelId/edit',
    path: '/catalog/models/$modelId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogModelsModelIdHistoryRoute =
  AppCatalogModelsModelIdHistoryRouteImport.update({
    id: '/catalog/models/$modelId/history',
    path: '/catalog/models/$modelId/history',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/audit': typeof AppAuditRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/warehouses': typeof AppAdminWarehousesRoute
  '/catalog/categories': typeof AppCatalogCategoriesRoute
  '/artists/': typeof AppArtistsIndexRoute
  '/parties/': typeof AppPartiesIndexRoute
  '/venues/': typeof AppVenuesIndexRoute
  '/artists/$partyId/history': typeof AppArtistsPartyIdHistoryRoute
  '/catalog/models/new': typeof AppCatalogModelsNewRoute
  '/parties/$partyId/history': typeof AppPartiesPartyIdHistoryRoute
  '/productions/$productionId/history': typeof AppProductionsProductionIdHistoryRoute
  '/venues/$venueId/equipment': typeof AppVenuesVenueIdEquipmentRoute
  '/venues/$venueId/history': typeof AppVenuesVenueIdHistoryRoute
  '/artists/$partyId/': typeof AppArtistsPartyIdIndexRoute
  '/catalog/kits/': typeof AppCatalogKitsIndexRoute
  '/catalog/models/': typeof AppCatalogModelsIndexRoute
  '/parties/$partyId/': typeof AppPartiesPartyIdIndexRoute
  '/productions/$productionId/': typeof AppProductionsProductionIdIndexRoute
  '/venues/$venueId/': typeof AppVenuesVenueIdIndexRoute
  '/catalog/kits/$kitId/history': typeof AppCatalogKitsKitIdHistoryRoute
  '/catalog/models/$modelId/edit': typeof AppCatalogModelsModelIdEditRoute
  '/catalog/models/$modelId/history': typeof AppCatalogModelsModelIdHistoryRoute
  '/catalog/kits/$kitId/': typeof AppCatalogKitsKitIdIndexRoute
  '/catalog/models/$modelId/': typeof AppCatalogModelsModelIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/audit': typeof AppAuditRoute
  '/': typeof AppIndexRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/warehouses': typeof AppAdminWarehousesRoute
  '/catalog/categories': typeof AppCatalogCategoriesRoute
  '/artists': typeof AppArtistsIndexRoute
  '/parties': typeof AppPartiesIndexRoute
  '/venues': typeof AppVenuesIndexRoute
  '/artists/$partyId/history': typeof AppArtistsPartyIdHistoryRoute
  '/catalog/models/new': typeof AppCatalogModelsNewRoute
  '/parties/$partyId/history': typeof AppPartiesPartyIdHistoryRoute
  '/productions/$productionId/history': typeof AppProductionsProductionIdHistoryRoute
  '/venues/$venueId/equipment': typeof AppVenuesVenueIdEquipmentRoute
  '/venues/$venueId/history': typeof AppVenuesVenueIdHistoryRoute
  '/artists/$partyId': typeof AppArtistsPartyIdIndexRoute
  '/catalog/kits': typeof AppCatalogKitsIndexRoute
  '/catalog/models': typeof AppCatalogModelsIndexRoute
  '/parties/$partyId': typeof AppPartiesPartyIdIndexRoute
  '/productions/$productionId': typeof AppProductionsProductionIdIndexRoute
  '/venues/$venueId': typeof AppVenuesVenueIdIndexRoute
  '/catalog/kits/$kitId/history': typeof AppCatalogKitsKitIdHistoryRoute
  '/catalog/models/$modelId/edit': typeof AppCatalogModelsModelIdEditRoute
  '/catalog/models/$modelId/history': typeof AppCatalogModelsModelIdHistoryRoute
  '/catalog/kits/$kitId': typeof AppCatalogKitsKitIdIndexRoute
  '/catalog/models/$modelId': typeof AppCatalogModelsModelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/warehouses': typeof AppAdminWarehousesRoute
  '/_app/catalog/categories': typeof AppCatalogCategoriesRoute
  '/_app/artists/': typeof AppArtistsIndexRoute
  '/_app/parties/': typeof AppPartiesIndexRoute
  '/_app/venues/': typeof AppVenuesIndexRoute
  '/_app/artists/$partyId/history': typeof AppArtistsPartyIdHistoryRoute
  '/_app/catalog/models/new': typeof AppCatalogModelsNewRoute
  '/_app/parties/$partyId/history': typeof AppPartiesPartyIdHistoryRoute
  '/_app/productions/$productionId/history': typeof AppProductionsProductionIdHistoryRoute
  '/_app/venues/$venueId/equipment': typeof AppVenuesVenueIdEquipmentRoute
  '/_app/venues/$venueId/history': typeof AppVenuesVenueIdHistoryRoute
  '/_app/artists/$partyId/': typeof AppArtistsPartyIdIndexRoute
  '/_app/catalog/kits/': typeof AppCatalogKitsIndexRoute
  '/_app/catalog/models/': typeof AppCatalogModelsIndexRoute
  '/_app/parties/$partyId/': typeof AppPartiesPartyIdIndexRoute
  '/_app/productions/$productionId/': typeof AppProductionsProductionIdIndexRoute
  '/_app/venues/$venueId/': typeof AppVenuesVenueIdIndexRoute
  '/_app/catalog/kits/$kitId/history': typeof AppCatalogKitsKitIdHistoryRoute
  '/_app/catalog/models/$modelId/edit': typeof AppCatalogModelsModelIdEditRoute
  '/_app/catalog/models/$modelId/history': typeof AppCatalogModelsModelIdHistoryRoute
  '/_app/catalog/kits/$kitId/': typeof AppCatalogKitsKitIdIndexRoute
  '/_app/catalog/models/$modelId/': typeof AppCatalogModelsModelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/set-password'
    | '/audit'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/warehouses'
    | '/catalog/categories'
    | '/artists/'
    | '/parties/'
    | '/venues/'
    | '/artists/$partyId/history'
    | '/catalog/models/new'
    | '/parties/$partyId/history'
    | '/productions/$productionId/history'
    | '/venues/$venueId/equipment'
    | '/venues/$venueId/history'
    | '/artists/$partyId/'
    | '/catalog/kits/'
    | '/catalog/models/'
    | '/parties/$partyId/'
    | '/productions/$productionId/'
    | '/venues/$venueId/'
    | '/catalog/kits/$kitId/history'
    | '/catalog/models/$modelId/edit'
    | '/catalog/models/$modelId/history'
    | '/catalog/kits/$kitId/'
    | '/catalog/models/$modelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/set-password'
    | '/audit'
    | '/'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/warehouses'
    | '/catalog/categories'
    | '/artists'
    | '/parties'
    | '/venues'
    | '/artists/$partyId/history'
    | '/catalog/models/new'
    | '/parties/$partyId/history'
    | '/productions/$productionId/history'
    | '/venues/$venueId/equipment'
    | '/venues/$venueId/history'
    | '/artists/$partyId'
    | '/catalog/kits'
    | '/catalog/models'
    | '/parties/$partyId'
    | '/productions/$productionId'
    | '/venues/$venueId'
    | '/catalog/kits/$kitId/history'
    | '/catalog/models/$modelId/edit'
    | '/catalog/models/$modelId/history'
    | '/catalog/kits/$kitId'
    | '/catalog/models/$modelId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/set-password'
    | '/_app/audit'
    | '/_app/'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/admin/warehouses'
    | '/_app/catalog/categories'
    | '/_app/artists/'
    | '/_app/parties/'
    | '/_app/venues/'
    | '/_app/artists/$partyId/history'
    | '/_app/catalog/models/new'
    | '/_app/parties/$partyId/history'
    | '/_app/productions/$productionId/history'
    | '/_app/venues/$venueId/equipment'
    | '/_app/venues/$venueId/history'
    | '/_app/artists/$partyId/'
    | '/_app/catalog/kits/'
    | '/_app/catalog/models/'
    | '/_app/parties/$partyId/'
    | '/_app/productions/$productionId/'
    | '/_app/venues/$venueId/'
    | '/_app/catalog/kits/$kitId/history'
    | '/_app/catalog/models/$modelId/edit'
    | '/_app/catalog/models/$modelId/history'
    | '/_app/catalog/kits/$kitId/'
    | '/_app/catalog/models/$modelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/warehouses': {
      id: '/_app/admin/warehouses'
      path: '/admin/warehouses'
      fullPath: '/admin/warehouses'
      preLoaderRoute: typeof AppAdminWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artists/': {
      id: '/_app/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof AppArtistsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/categories': {
      id: '/_app/catalog/categories'
      path: '/catalog/categories'
      fullPath: '/catalog/categories'
      preLoaderRoute: typeof AppCatalogCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties/': {
      id: '/_app/parties/'
      path: '/parties'
      fullPath: '/parties/'
      preLoaderRoute: typeof AppPartiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/venues/': {
      id: '/_app/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof AppVenuesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artists/$partyId/': {
      id: '/_app/artists/$partyId/'
      path: '/artists/$partyId'
      fullPath: '/artists/$partyId/'
      preLoaderRoute: typeof AppArtistsPartyIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artists/$partyId/history': {
      id: '/_app/artists/$partyId/history'
      path: '/artists/$partyId/history'
      fullPath: '/artists/$partyId/history'
      preLoaderRoute: typeof AppArtistsPartyIdHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/kits/': {
      id: '/_app/catalog/kits/'
      path: '/catalog/kits'
      fullPath: '/catalog/kits/'
      preLoaderRoute: typeof AppCatalogKitsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/models/': {
      id: '/_app/catalog/models/'
      path: '/catalog/models'
      fullPath: '/catalog/models/'
      preLoaderRoute: typeof AppCatalogModelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/models/new': {
      id: '/_app/catalog/models/new'
      path: '/catalog/models/new'
      fullPath: '/catalog/models/new'
      preLoaderRoute: typeof AppCatalogModelsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties/$partyId/': {
      id: '/_app/parties/$partyId/'
      path: '/parties/$partyId'
      fullPath: '/parties/$partyId/'
      preLoaderRoute: typeof AppPartiesPartyIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties/$partyId/history': {
      id: '/_app/parties/$partyId/history'
      path: '/parties/$partyId/history'
      fullPath: '/parties/$partyId/history'
      preLoaderRoute: typeof AppPartiesPartyIdHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/productions/$productionId/': {
      id: '/_app/productions/$productionId/'
      path: '/productions/$productionId'
      fullPath: '/productions/$productionId/'
      preLoaderRoute: typeof AppProductionsProductionIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/productions/$productionId/history': {
      id: '/_app/productions/$productionId/history'
      path: '/productions/$productionId/history'
      fullPath: '/productions/$productionId/history'
      preLoaderRoute: typeof AppProductionsProductionIdHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/venues/$venueId/': {
      id: '/_app/venues/$venueId/'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId/'
      preLoaderRoute: typeof AppVenuesVenueIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/venues/$venueId/equipment': {
      id: '/_app/venues/$venueId/equipment'
      path: '/venues/$venueId/equipment'
      fullPath: '/venues/$venueId/equipment'
      preLoaderRoute: typeof AppVenuesVenueIdEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/venues/$venueId/history': {
      id: '/_app/venues/$venueId/history'
      path: '/venues/$venueId/history'
      fullPath: '/venues/$venueId/history'
      preLoaderRoute: typeof AppVenuesVenueIdHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/kits/$kitId/': {
      id: '/_app/catalog/kits/$kitId/'
      path: '/catalog/kits/$kitId'
      fullPath: '/catalog/kits/$kitId/'
      preLoaderRoute: typeof AppCatalogKitsKitIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/kits/$kitId/history': {
      id: '/_app/catalog/kits/$kitId/history'
      path: '/catalog/kits/$kitId/history'
      fullPath: '/catalog/kits/$kitId/history'
      preLoaderRoute: typeof AppCatalogKitsKitIdHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/models/$modelId/': {
      id: '/_app/catalog/models/$modelId/'
      path: '/catalog/models/$modelId'
      fullPath: '/catalog/models/$modelId/'
      preLoaderRoute: typeof AppCatalogModelsModelIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/models/$modelId/edit': {
      id: '/_app/catalog/models/$modelId/edit'
      path: '/catalog/models/$modelId/edit'
      fullPath: '/catalog/models/$modelId/edit'
      preLoaderRoute: typeof AppCatalogModelsModelIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/models/$modelId/history': {
      id: '/_app/catalog/models/$modelId/history'
      path: '/catalog/models/$modelId/history'
      fullPath: '/catalog/models/$modelId/history'
      preLoaderRoute: typeof AppCatalogModelsModelIdHistoryRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminWarehousesRoute: typeof AppAdminWarehousesRoute
  AppCatalogCategoriesRoute: typeof AppCatalogCategoriesRoute
  AppArtistsIndexRoute: typeof AppArtistsIndexRoute
  AppPartiesIndexRoute: typeof AppPartiesIndexRoute
  AppVenuesIndexRoute: typeof AppVenuesIndexRoute
  AppArtistsPartyIdHistoryRoute: typeof AppArtistsPartyIdHistoryRoute
  AppCatalogModelsNewRoute: typeof AppCatalogModelsNewRoute
  AppPartiesPartyIdHistoryRoute: typeof AppPartiesPartyIdHistoryRoute
  AppProductionsProductionIdHistoryRoute: typeof AppProductionsProductionIdHistoryRoute
  AppVenuesVenueIdEquipmentRoute: typeof AppVenuesVenueIdEquipmentRoute
  AppVenuesVenueIdHistoryRoute: typeof AppVenuesVenueIdHistoryRoute
  AppArtistsPartyIdIndexRoute: typeof AppArtistsPartyIdIndexRoute
  AppCatalogKitsIndexRoute: typeof AppCatalogKitsIndexRoute
  AppCatalogModelsIndexRoute: typeof AppCatalogModelsIndexRoute
  AppPartiesPartyIdIndexRoute: typeof AppPartiesPartyIdIndexRoute
  AppProductionsProductionIdIndexRoute: typeof AppProductionsProductionIdIndexRoute
  AppVenuesVenueIdIndexRoute: typeof AppVenuesVenueIdIndexRoute
  AppCatalogKitsKitIdHistoryRoute: typeof AppCatalogKitsKitIdHistoryRoute
  AppCatalogModelsModelIdEditRoute: typeof AppCatalogModelsModelIdEditRoute
  AppCatalogModelsModelIdHistoryRoute: typeof AppCatalogModelsModelIdHistoryRoute
  AppCatalogKitsKitIdIndexRoute: typeof AppCatalogKitsKitIdIndexRoute
  AppCatalogModelsModelIdIndexRoute: typeof AppCatalogModelsModelIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminWarehousesRoute: AppAdminWarehousesRoute,
  AppCatalogCategoriesRoute: AppCatalogCategoriesRoute,
  AppArtistsIndexRoute: AppArtistsIndexRoute,
  AppPartiesIndexRoute: AppPartiesIndexRoute,
  AppVenuesIndexRoute: AppVenuesIndexRoute,
  AppArtistsPartyIdHistoryRoute: AppArtistsPartyIdHistoryRoute,
  AppCatalogModelsNewRoute: AppCatalogModelsNewRoute,
  AppPartiesPartyIdHistoryRoute: AppPartiesPartyIdHistoryRoute,
  AppProductionsProductionIdHistoryRoute:
    AppProductionsProductionIdHistoryRoute,
  AppVenuesVenueIdEquipmentRoute: AppVenuesVenueIdEquipmentRoute,
  AppVenuesVenueIdHistoryRoute: AppVenuesVenueIdHistoryRoute,
  AppArtistsPartyIdIndexRoute: AppArtistsPartyIdIndexRoute,
  AppCatalogKitsIndexRoute: AppCatalogKitsIndexRoute,
  AppCatalogModelsIndexRoute: AppCatalogModelsIndexRoute,
  AppPartiesPartyIdIndexRoute: AppPartiesPartyIdIndexRoute,
  AppProductionsProductionIdIndexRoute: AppProductionsProductionIdIndexRoute,
  AppVenuesVenueIdIndexRoute: AppVenuesVenueIdIndexRoute,
  AppCatalogKitsKitIdHistoryRoute: AppCatalogKitsKitIdHistoryRoute,
  AppCatalogModelsModelIdEditRoute: AppCatalogModelsModelIdEditRoute,
  AppCatalogModelsModelIdHistoryRoute: AppCatalogModelsModelIdHistoryRoute,
  AppCatalogKitsKitIdIndexRoute: AppCatalogKitsKitIdIndexRoute,
  AppCatalogModelsModelIdIndexRoute: AppCatalogModelsModelIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
