/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminWarehousesRouteImport } from './routes/_app/admin/warehouses'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminWarehousesRoute = AppAdminWarehousesRouteImport.update({
  id: '/admin/warehouses',
  path: '/admin/warehouses',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/audit': typeof AppAuditRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/warehouses': typeof AppAdminWarehousesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/audit': typeof AppAuditRoute
  '/': typeof AppIndexRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/warehouses': typeof AppAdminWarehousesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/warehouses': typeof AppAdminWarehousesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/set-password'
    | '/audit'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/warehouses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/set-password'
    | '/audit'
    | '/'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/warehouses'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/set-password'
    | '/_app/audit'
    | '/_app/'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/admin/warehouses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/warehouses': {
      id: '/_app/admin/warehouses'
      path: '/admin/warehouses'
      fullPath: '/admin/warehouses'
      preLoaderRoute: typeof AppAdminWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminWarehousesRoute: typeof AppAdminWarehousesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminWarehousesRoute: AppAdminWarehousesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
