/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


/**
 * @summary Lists the productions, searched and filtered, one page at a time.
 */
export const ListProductionsQueryParams = zod.object({
  "artistId": zod.uuid().optional(),
  "q": zod.string().optional(),
  "status": zod.enum(['active', 'inactive', 'all']).optional(),
  "sort": zod.string().optional(),
  "page": zod.int().optional(),
  "pageSize": zod.int().optional()
})

export const ListProductionsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "artistPartyId": zod.uuid(),
  "artistName": zod.string().nullable(),
  "name": zod.string(),
  "latestVersionNumber": zod.int(),
  "isActive": zod.boolean(),
  "version": zod.int()
})),
  "page": zod.int(),
  "pageSize": zod.int(),
  "totalCount": zod.int()
})

/**
 * @summary Records an artist's production and opens its empty rider.
 */
export const CreateProductionHeader = zod.object({
  "Idempotency-Key": zod.uuid().describe('A new UUID for each user action, and the same one when the action is retried (api §10).')
})

export const CreateProductionBody = zod.object({
  "artistPartyId": zod.uuid(),
  "name": zod.string(),
  "description": zod.string().nullish()
})

export const CreateProductionResponse = zod.object({
  "id": zod.uuid(),
  "artistPartyId": zod.uuid(),
  "artistName": zod.string().nullable(),
  "isArtistActive": zod.boolean(),
  "name": zod.string(),
  "description": zod.string().nullable(),
  "riderId": zod.uuid(),
  "riderVersion": zod.int(),
  "latestVersionNumber": zod.int(),
  "deactivatedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "version": zod.int()
})

/**
 * @summary Gets a production with its artist's name and its rider.
 */
export const GetProductionParams = zod.object({
  "productionId": zod.uuid()
})

export const GetProductionResponse = zod.object({
  "id": zod.uuid(),
  "artistPartyId": zod.uuid(),
  "artistName": zod.string().nullable(),
  "isArtistActive": zod.boolean(),
  "name": zod.string(),
  "description": zod.string().nullable(),
  "riderId": zod.uuid(),
  "riderVersion": zod.int(),
  "latestVersionNumber": zod.int(),
  "deactivatedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "version": zod.int()
})

/**
 * @summary Changes a production's name and description.
 */
export const EditProductionParams = zod.object({
  "productionId": zod.uuid()
})

export const EditProductionHeader = zod.object({
  "If-Match": zod.string().describe('The version the change is based on, as a strong entity tag, e.g. "7" (api §9).'),
  "Idempotency-Key": zod.uuid().describe('A new UUID for each user action, and the same one when the action is retried (api §10).')
})

export const EditProductionBody = zod.object({
  "name": zod.string(),
  "description": zod.string().nullish()
})

export const EditProductionResponse = zod.object({
  "id": zod.uuid(),
  "artistPartyId": zod.uuid(),
  "artistName": zod.string().nullable(),
  "isArtistActive": zod.boolean(),
  "name": zod.string(),
  "description": zod.string().nullable(),
  "riderId": zod.uuid(),
  "riderVersion": zod.int(),
  "latestVersionNumber": zod.int(),
  "deactivatedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "version": zod.int()
})

/**
 * @summary Takes a production out of new selections.
 */
export const DeactivateProductionParams = zod.object({
  "productionId": zod.uuid()
})

export const DeactivateProductionHeader = zod.object({
  "If-Match": zod.string().describe('The version the change is based on, as a strong entity tag, e.g. "7" (api §9).'),
  "Idempotency-Key": zod.uuid().describe('A new UUID for each user action, and the same one when the action is retried (api §10).')
})

export const DeactivateProductionResponse = zod.object({
  "id": zod.uuid(),
  "artistPartyId": zod.uuid(),
  "artistName": zod.string().nullable(),
  "isArtistActive": zod.boolean(),
  "name": zod.string(),
  "description": zod.string().nullable(),
  "riderId": zod.uuid(),
  "riderVersion": zod.int(),
  "latestVersionNumber": zod.int(),
  "deactivatedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "version": zod.int()
})

/**
 * @summary Activates a deactivated production again.
 */
export const ActivateProductionParams = zod.object({
  "productionId": zod.uuid()
})

export const ActivateProductionHeader = zod.object({
  "If-Match": zod.string().describe('The version the change is based on, as a strong entity tag, e.g. "7" (api §9).'),
  "Idempotency-Key": zod.uuid().describe('A new UUID for each user action, and the same one when the action is retried (api §10).')
})

export const ActivateProductionResponse = zod.object({
  "id": zod.uuid(),
  "artistPartyId": zod.uuid(),
  "artistName": zod.string().nullable(),
  "isArtistActive": zod.boolean(),
  "name": zod.string(),
  "description": zod.string().nullable(),
  "riderId": zod.uuid(),
  "riderVersion": zod.int(),
  "latestVersionNumber": zod.int(),
  "deactivatedAt": zod.iso.datetime({"offset":true}).nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "version": zod.int()
})

