<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\FestOS.BuildingBlocks.Application\FestOS.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\FestOS.Modules.Identity.Domain\FestOS.Modules.Identity.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FestOS.Modules.Identity.UnitTests" />
    <InternalsVisibleTo Include="FestOS.Modules.Identity.IntegrationTests" />
  </ItemGroup>
</Project>
