/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiProblem,
  ListVenuesParams,
  PagedResultOfVenueListItem,
  VenueDetails,
  VenueRequest
} from '../../model';

import { apiClient } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListVenuesUrl = (params?: ListVenuesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/venues?${stringifiedParams}` : `/api/v1/venues`
}

/**
 * @summary Lists the venues, searched and filtered, one page at a time.
 */
export const listVenues = async (params?: ListVenuesParams, options?: Parameters<typeof apiClient>[1]): Promise<PagedResultOfVenueListItem> => {

  return apiClient<PagedResultOfVenueListItem>(getListVenuesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListVenuesQueryKey = (params?: ListVenuesParams,) => {
    return [
    `/api/v1/venues`, ...(params ? [params] : [])
    ] as const;
    }


export const getListVenuesQueryOptions = <TData = Awaited<ReturnType<typeof listVenues>>, TError = ApiProblem>(params?: ListVenuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVenues>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVenuesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVenues>>> = ({ signal }) => listVenues(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVenues>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVenuesQueryResult = NonNullable<Awaited<ReturnType<typeof listVenues>>>
export type ListVenuesQueryError = ApiProblem


export function useListVenues<TData = Awaited<ReturnType<typeof listVenues>>, TError = ApiProblem>(
 params: undefined |  ListVenuesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVenues>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVenues>>,
          TError,
          Awaited<ReturnType<typeof listVenues>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVenues<TData = Awaited<ReturnType<typeof listVenues>>, TError = ApiProblem>(
 params?: ListVenuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVenues>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVenues>>,
          TError,
          Awaited<ReturnType<typeof listVenues>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVenues<TData = Awaited<ReturnType<typeof listVenues>>, TError = ApiProblem>(
 params?: ListVenuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVenues>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lists the venues, searched and filtered, one page at a time.
 */

export function useListVenues<TData = Awaited<ReturnType<typeof listVenues>>, TError = ApiProblem>(
 params?: ListVenuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVenues>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVenuesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateVenueUrl = () => {




  return `/api/v1/venues`
}

/**
 * @summary Records a venue with its technical details.
 */
export const createVenue = async (venueRequest: VenueRequest, options?: Parameters<typeof apiClient>[1]): Promise<VenueDetails> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiClient<VenueDetails>(getCreateVenueUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(venueRequest)
  }
);}





export const getCreateVenueMutationKey = () => ['createVenue'] as const;

export const getCreateVenueMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVenue>>, TError,CreateVenueMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createVenue>>, TError,CreateVenueMutationVariables, TContext> => {

const mutationKey = getCreateVenueMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createVenue>>, CreateVenueMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createVenue(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateVenueMutationResult = NonNullable<Awaited<ReturnType<typeof createVenue>>>
    export type CreateVenueMutationBody = VenueRequest
    export type CreateVenueMutationError = ApiProblem
    export type CreateVenueMutationVariables = {data: VenueRequest}

    /**
 * @summary Records a venue with its technical details.
 */
export const useCreateVenue = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVenue>>, TError,CreateVenueMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createVenue>>,
        TError,
        CreateVenueMutationVariables,
        TContext
      > => {
      return useMutation(getCreateVenueMutationOptions(options), queryClient);
    }
    export const getGetVenueUrl = (venueId: string,) => {




  return `/api/v1/venues/${venueId}`
}

/**
 * @summary Gets a venue with its operator's name.
 */
export const getVenue = async (venueId: string, options?: Parameters<typeof apiClient>[1]): Promise<VenueDetails> => {

  return apiClient<VenueDetails>(getGetVenueUrl(venueId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetVenueQueryKey = (venueId: string,) => {
    return [
    `/api/v1/venues/${venueId}`
    ] as const;
    }


export const getGetVenueQueryOptions = <TData = Awaited<ReturnType<typeof getVenue>>, TError = ApiProblem>(venueId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenue>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVenueQueryKey(venueId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVenue>>> = ({ signal }) => getVenue(venueId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: venueId !== null && venueId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVenue>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVenueQueryResult = NonNullable<Awaited<ReturnType<typeof getVenue>>>
export type GetVenueQueryError = ApiProblem


export function useGetVenue<TData = Awaited<ReturnType<typeof getVenue>>, TError = ApiProblem>(
 venueId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenue>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVenue>>,
          TError,
          Awaited<ReturnType<typeof getVenue>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVenue<TData = Awaited<ReturnType<typeof getVenue>>, TError = ApiProblem>(
 venueId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenue>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVenue>>,
          TError,
          Awaited<ReturnType<typeof getVenue>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVenue<TData = Awaited<ReturnType<typeof getVenue>>, TError = ApiProblem>(
 venueId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenue>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Gets a venue with its operator's name.
 */

export function useGetVenue<TData = Awaited<ReturnType<typeof getVenue>>, TError = ApiProblem>(
 venueId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenue>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVenueQueryOptions(venueId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getEditVenueUrl = (venueId: string,) => {




  return `/api/v1/venues/${venueId}`
}

/**
 * @summary Changes a venue's details.
 */
export const editVenue = async (venueId: string,
    venueRequest: VenueRequest, options?: Parameters<typeof apiClient>[1]): Promise<VenueDetails> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiClient<VenueDetails>(getEditVenueUrl(venueId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(venueRequest)
  }
);}





export const getEditVenueMutationKey = () => ['editVenue'] as const;

export const getEditVenueMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editVenue>>, TError,EditVenueMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof editVenue>>, TError,EditVenueMutationVariables, TContext> => {

const mutationKey = getEditVenueMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editVenue>>, EditVenueMutationVariables> = (props) => {
          const {venueId,data} = props ?? {};

          return  editVenue(venueId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditVenueMutationResult = NonNullable<Awaited<ReturnType<typeof editVenue>>>
    export type EditVenueMutationBody = VenueRequest
    export type EditVenueMutationError = ApiProblem
    export type EditVenueMutationVariables = {venueId: string;data: VenueRequest}

    /**
 * @summary Changes a venue's details.
 */
export const useEditVenue = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editVenue>>, TError,EditVenueMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editVenue>>,
        TError,
        EditVenueMutationVariables,
        TContext
      > => {
      return useMutation(getEditVenueMutationOptions(options), queryClient);
    }
    export const getDeactivateVenueUrl = (venueId: string,) => {




  return `/api/v1/venues/${venueId}/deactivate`
}

/**
 * @summary Takes a venue out of new selections.
 */
export const deactivateVenue = async (venueId: string, options?: Parameters<typeof apiClient>[1]): Promise<VenueDetails> => {

  return apiClient<VenueDetails>(getDeactivateVenueUrl(venueId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDeactivateVenueMutationKey = () => ['deactivateVenue'] as const;

export const getDeactivateVenueMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateVenue>>, TError,DeactivateVenueMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deactivateVenue>>, TError,DeactivateVenueMutationVariables, TContext> => {

const mutationKey = getDeactivateVenueMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivateVenue>>, DeactivateVenueMutationVariables> = (props) => {
          const {venueId} = props ?? {};

          return  deactivateVenue(venueId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivateVenueMutationResult = NonNullable<Awaited<ReturnType<typeof deactivateVenue>>>

    export type DeactivateVenueMutationError = ApiProblem
    export type DeactivateVenueMutationVariables = {venueId: string}

    /**
 * @summary Takes a venue out of new selections.
 */
export const useDeactivateVenue = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateVenue>>, TError,DeactivateVenueMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivateVenue>>,
        TError,
        DeactivateVenueMutationVariables,
        TContext
      > => {
      return useMutation(getDeactivateVenueMutationOptions(options), queryClient);
    }
    export const getActivateVenueUrl = (venueId: string,) => {




  return `/api/v1/venues/${venueId}/activate`
}

/**
 * @summary Activates a deactivated venue again.
 */
export const activateVenue = async (venueId: string, options?: Parameters<typeof apiClient>[1]): Promise<VenueDetails> => {

  return apiClient<VenueDetails>(getActivateVenueUrl(venueId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getActivateVenueMutationKey = () => ['activateVenue'] as const;

export const getActivateVenueMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateVenue>>, TError,ActivateVenueMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof activateVenue>>, TError,ActivateVenueMutationVariables, TContext> => {

const mutationKey = getActivateVenueMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateVenue>>, ActivateVenueMutationVariables> = (props) => {
          const {venueId} = props ?? {};

          return  activateVenue(venueId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateVenueMutationResult = NonNullable<Awaited<ReturnType<typeof activateVenue>>>

    export type ActivateVenueMutationError = ApiProblem
    export type ActivateVenueMutationVariables = {venueId: string}

    /**
 * @summary Activates a deactivated venue again.
 */
export const useActivateVenue = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateVenue>>, TError,ActivateVenueMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateVenue>>,
        TError,
        ActivateVenueMutationVariables,
        TContext
      > => {
      return useMutation(getActivateVenueMutationOptions(options), queryClient);
    }
