/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiProblem,
  CreateProductionRequest,
  EditProductionRequest,
  ListProductionsParams,
  PagedResultOfProductionListItem,
  ProductionDetails
} from '../../model';

import { apiClient } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListProductionsUrl = (params?: ListProductionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/productions?${stringifiedParams}` : `/api/v1/productions`
}

/**
 * @summary Lists the productions, searched and filtered, one page at a time.
 */
export const listProductions = async (params?: ListProductionsParams, options?: Parameters<typeof apiClient>[1]): Promise<PagedResultOfProductionListItem> => {

  return apiClient<PagedResultOfProductionListItem>(getListProductionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListProductionsQueryKey = (params?: ListProductionsParams,) => {
    return [
    `/api/v1/productions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListProductionsQueryOptions = <TData = Awaited<ReturnType<typeof listProductions>>, TError = ApiProblem>(params?: ListProductionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProductions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProductionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProductions>>> = ({ signal }) => listProductions(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProductions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProductionsQueryResult = NonNullable<Awaited<ReturnType<typeof listProductions>>>
export type ListProductionsQueryError = ApiProblem


export function useListProductions<TData = Awaited<ReturnType<typeof listProductions>>, TError = ApiProblem>(
 params: undefined |  ListProductionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProductions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProductions>>,
          TError,
          Awaited<ReturnType<typeof listProductions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProductions<TData = Awaited<ReturnType<typeof listProductions>>, TError = ApiProblem>(
 params?: ListProductionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProductions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProductions>>,
          TError,
          Awaited<ReturnType<typeof listProductions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProductions<TData = Awaited<ReturnType<typeof listProductions>>, TError = ApiProblem>(
 params?: ListProductionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProductions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lists the productions, searched and filtered, one page at a time.
 */

export function useListProductions<TData = Awaited<ReturnType<typeof listProductions>>, TError = ApiProblem>(
 params?: ListProductionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProductions>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProductionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreateProductionUrl = () => {




  return `/api/v1/productions`
}

/**
 * @summary Records an artist's production and opens its empty rider.
 */
export const createProduction = async (createProductionRequest: CreateProductionRequest, options?: Parameters<typeof apiClient>[1]): Promise<ProductionDetails> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiClient<ProductionDetails>(getCreateProductionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createProductionRequest)
  }
);}





export const getCreateProductionMutationKey = () => ['createProduction'] as const;

export const getCreateProductionMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduction>>, TError,CreateProductionMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createProduction>>, TError,CreateProductionMutationVariables, TContext> => {

const mutationKey = getCreateProductionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProduction>>, CreateProductionMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createProduction(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProductionMutationResult = NonNullable<Awaited<ReturnType<typeof createProduction>>>
    export type CreateProductionMutationBody = CreateProductionRequest
    export type CreateProductionMutationError = ApiProblem
    export type CreateProductionMutationVariables = {data: CreateProductionRequest}

    /**
 * @summary Records an artist's production and opens its empty rider.
 */
export const useCreateProduction = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduction>>, TError,CreateProductionMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProduction>>,
        TError,
        CreateProductionMutationVariables,
        TContext
      > => {
      return useMutation(getCreateProductionMutationOptions(options), queryClient);
    }
    export const getGetProductionUrl = (productionId: string,) => {




  return `/api/v1/productions/${productionId}`
}

/**
 * @summary Gets a production with its artist's name and its rider.
 */
export const getProduction = async (productionId: string, options?: Parameters<typeof apiClient>[1]): Promise<ProductionDetails> => {

  return apiClient<ProductionDetails>(getGetProductionUrl(productionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProductionQueryKey = (productionId: string,) => {
    return [
    `/api/v1/productions/${productionId}`
    ] as const;
    }


export const getGetProductionQueryOptions = <TData = Awaited<ReturnType<typeof getProduction>>, TError = ApiProblem>(productionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduction>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductionQueryKey(productionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProduction>>> = ({ signal }) => getProduction(productionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: productionId !== null && productionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProduction>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductionQueryResult = NonNullable<Awaited<ReturnType<typeof getProduction>>>
export type GetProductionQueryError = ApiProblem


export function useGetProduction<TData = Awaited<ReturnType<typeof getProduction>>, TError = ApiProblem>(
 productionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduction>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProduction>>,
          TError,
          Awaited<ReturnType<typeof getProduction>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProduction<TData = Awaited<ReturnType<typeof getProduction>>, TError = ApiProblem>(
 productionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduction>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProduction>>,
          TError,
          Awaited<ReturnType<typeof getProduction>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProduction<TData = Awaited<ReturnType<typeof getProduction>>, TError = ApiProblem>(
 productionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduction>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Gets a production with its artist's name and its rider.
 */

export function useGetProduction<TData = Awaited<ReturnType<typeof getProduction>>, TError = ApiProblem>(
 productionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduction>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductionQueryOptions(productionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getEditProductionUrl = (productionId: string,) => {




  return `/api/v1/productions/${productionId}`
}

/**
 * @summary Changes a production's name and description.
 */
export const editProduction = async (productionId: string,
    editProductionRequest: EditProductionRequest, options?: Parameters<typeof apiClient>[1]): Promise<ProductionDetails> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiClient<ProductionDetails>(getEditProductionUrl(productionId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(editProductionRequest)
  }
);}





export const getEditProductionMutationKey = () => ['editProduction'] as const;

export const getEditProductionMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editProduction>>, TError,EditProductionMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof editProduction>>, TError,EditProductionMutationVariables, TContext> => {

const mutationKey = getEditProductionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editProduction>>, EditProductionMutationVariables> = (props) => {
          const {productionId,data} = props ?? {};

          return  editProduction(productionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditProductionMutationResult = NonNullable<Awaited<ReturnType<typeof editProduction>>>
    export type EditProductionMutationBody = EditProductionRequest
    export type EditProductionMutationError = ApiProblem
    export type EditProductionMutationVariables = {productionId: string;data: EditProductionRequest}

    /**
 * @summary Changes a production's name and description.
 */
export const useEditProduction = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editProduction>>, TError,EditProductionMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editProduction>>,
        TError,
        EditProductionMutationVariables,
        TContext
      > => {
      return useMutation(getEditProductionMutationOptions(options), queryClient);
    }
    export const getDeactivateProductionUrl = (productionId: string,) => {




  return `/api/v1/productions/${productionId}/deactivate`
}

/**
 * @summary Takes a production out of new selections.
 */
export const deactivateProduction = async (productionId: string, options?: Parameters<typeof apiClient>[1]): Promise<ProductionDetails> => {

  return apiClient<ProductionDetails>(getDeactivateProductionUrl(productionId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDeactivateProductionMutationKey = () => ['deactivateProduction'] as const;

export const getDeactivateProductionMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateProduction>>, TError,DeactivateProductionMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deactivateProduction>>, TError,DeactivateProductionMutationVariables, TContext> => {

const mutationKey = getDeactivateProductionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivateProduction>>, DeactivateProductionMutationVariables> = (props) => {
          const {productionId} = props ?? {};

          return  deactivateProduction(productionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivateProductionMutationResult = NonNullable<Awaited<ReturnType<typeof deactivateProduction>>>

    export type DeactivateProductionMutationError = ApiProblem
    export type DeactivateProductionMutationVariables = {productionId: string}

    /**
 * @summary Takes a production out of new selections.
 */
export const useDeactivateProduction = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateProduction>>, TError,DeactivateProductionMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivateProduction>>,
        TError,
        DeactivateProductionMutationVariables,
        TContext
      > => {
      return useMutation(getDeactivateProductionMutationOptions(options), queryClient);
    }
    export const getActivateProductionUrl = (productionId: string,) => {




  return `/api/v1/productions/${productionId}/activate`
}

/**
 * @summary Activates a deactivated production again.
 */
export const activateProduction = async (productionId: string, options?: Parameters<typeof apiClient>[1]): Promise<ProductionDetails> => {

  return apiClient<ProductionDetails>(getActivateProductionUrl(productionId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getActivateProductionMutationKey = () => ['activateProduction'] as const;

export const getActivateProductionMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateProduction>>, TError,ActivateProductionMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof activateProduction>>, TError,ActivateProductionMutationVariables, TContext> => {

const mutationKey = getActivateProductionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateProduction>>, ActivateProductionMutationVariables> = (props) => {
          const {productionId} = props ?? {};

          return  activateProduction(productionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateProductionMutationResult = NonNullable<Awaited<ReturnType<typeof activateProduction>>>

    export type ActivateProductionMutationError = ApiProblem
    export type ActivateProductionMutationVariables = {productionId: string}

    /**
 * @summary Activates a deactivated production again.
 */
export const useActivateProduction = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateProduction>>, TError,ActivateProductionMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateProduction>>,
        TError,
        ActivateProductionMutationVariables,
        TContext
      > => {
      return useMutation(getActivateProductionMutationOptions(options), queryClient);
    }
