/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FestOS API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiProblem,
  ListPartiesParams,
  PagedResultOfPartyListItem,
  PartyDetails,
  PartyRequest
} from '../../model';

import { apiClient } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListPartiesUrl = (params?: ListPartiesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/parties?${stringifiedParams}` : `/api/v1/parties`
}

/**
 * @summary Lists the parties, searched and filtered, one page at a time.
 */
export const listParties = async (params?: ListPartiesParams, options?: Parameters<typeof apiClient>[1]): Promise<PagedResultOfPartyListItem> => {

  return apiClient<PagedResultOfPartyListItem>(getListPartiesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPartiesQueryKey = (params?: ListPartiesParams,) => {
    return [
    `/api/v1/parties`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPartiesQueryOptions = <TData = Awaited<ReturnType<typeof listParties>>, TError = ApiProblem>(params?: ListPartiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParties>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPartiesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listParties>>> = ({ signal }) => listParties(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listParties>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPartiesQueryResult = NonNullable<Awaited<ReturnType<typeof listParties>>>
export type ListPartiesQueryError = ApiProblem


export function useListParties<TData = Awaited<ReturnType<typeof listParties>>, TError = ApiProblem>(
 params: undefined |  ListPartiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParties>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listParties>>,
          TError,
          Awaited<ReturnType<typeof listParties>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListParties<TData = Awaited<ReturnType<typeof listParties>>, TError = ApiProblem>(
 params?: ListPartiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParties>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listParties>>,
          TError,
          Awaited<ReturnType<typeof listParties>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListParties<TData = Awaited<ReturnType<typeof listParties>>, TError = ApiProblem>(
 params?: ListPartiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParties>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lists the parties, searched and filtered, one page at a time.
 */

export function useListParties<TData = Awaited<ReturnType<typeof listParties>>, TError = ApiProblem>(
 params?: ListPartiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParties>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPartiesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCreatePartyUrl = () => {




  return `/api/v1/parties`
}

/**
 * @summary Creates a person or organization with its roles and contact points.
 */
export const createParty = async (partyRequest: PartyRequest, options?: Parameters<typeof apiClient>[1]): Promise<PartyDetails> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiClient<PartyDetails>(getCreatePartyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(partyRequest)
  }
);}





export const getCreatePartyMutationKey = () => ['createParty'] as const;

export const getCreatePartyMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createParty>>, TError,CreatePartyMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createParty>>, TError,CreatePartyMutationVariables, TContext> => {

const mutationKey = getCreatePartyMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createParty>>, CreatePartyMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createParty(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePartyMutationResult = NonNullable<Awaited<ReturnType<typeof createParty>>>
    export type CreatePartyMutationBody = PartyRequest
    export type CreatePartyMutationError = ApiProblem
    export type CreatePartyMutationVariables = {data: PartyRequest}

    /**
 * @summary Creates a person or organization with its roles and contact points.
 */
export const useCreateParty = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createParty>>, TError,CreatePartyMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createParty>>,
        TError,
        CreatePartyMutationVariables,
        TContext
      > => {
      return useMutation(getCreatePartyMutationOptions(options), queryClient);
    }
    export const getGetPartyUrl = (partyId: string,) => {




  return `/api/v1/parties/${partyId}`
}

/**
 * @summary Gets a party with its contact points.
 */
export const getParty = async (partyId: string, options?: Parameters<typeof apiClient>[1]): Promise<PartyDetails> => {

  return apiClient<PartyDetails>(getGetPartyUrl(partyId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPartyQueryKey = (partyId: string,) => {
    return [
    `/api/v1/parties/${partyId}`
    ] as const;
    }


export const getGetPartyQueryOptions = <TData = Awaited<ReturnType<typeof getParty>>, TError = ApiProblem>(partyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getParty>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPartyQueryKey(partyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getParty>>> = ({ signal }) => getParty(partyId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: partyId !== null && partyId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getParty>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPartyQueryResult = NonNullable<Awaited<ReturnType<typeof getParty>>>
export type GetPartyQueryError = ApiProblem


export function useGetParty<TData = Awaited<ReturnType<typeof getParty>>, TError = ApiProblem>(
 partyId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getParty>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getParty>>,
          TError,
          Awaited<ReturnType<typeof getParty>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetParty<TData = Awaited<ReturnType<typeof getParty>>, TError = ApiProblem>(
 partyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getParty>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getParty>>,
          TError,
          Awaited<ReturnType<typeof getParty>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetParty<TData = Awaited<ReturnType<typeof getParty>>, TError = ApiProblem>(
 partyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getParty>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Gets a party with its contact points.
 */

export function useGetParty<TData = Awaited<ReturnType<typeof getParty>>, TError = ApiProblem>(
 partyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getParty>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPartyQueryOptions(partyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getEditPartyUrl = (partyId: string,) => {




  return `/api/v1/parties/${partyId}`
}

/**
 * @summary Changes a party's names, roles and contact points.
 */
export const editParty = async (partyId: string,
    partyRequest: PartyRequest, options?: Parameters<typeof apiClient>[1]): Promise<PartyDetails> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiClient<PartyDetails>(getEditPartyUrl(partyId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(partyRequest)
  }
);}





export const getEditPartyMutationKey = () => ['editParty'] as const;

export const getEditPartyMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editParty>>, TError,EditPartyMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof editParty>>, TError,EditPartyMutationVariables, TContext> => {

const mutationKey = getEditPartyMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editParty>>, EditPartyMutationVariables> = (props) => {
          const {partyId,data} = props ?? {};

          return  editParty(partyId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditPartyMutationResult = NonNullable<Awaited<ReturnType<typeof editParty>>>
    export type EditPartyMutationBody = PartyRequest
    export type EditPartyMutationError = ApiProblem
    export type EditPartyMutationVariables = {partyId: string;data: PartyRequest}

    /**
 * @summary Changes a party's names, roles and contact points.
 */
export const useEditParty = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editParty>>, TError,EditPartyMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editParty>>,
        TError,
        EditPartyMutationVariables,
        TContext
      > => {
      return useMutation(getEditPartyMutationOptions(options), queryClient);
    }
    export const getDeactivatePartyUrl = (partyId: string,) => {




  return `/api/v1/parties/${partyId}/deactivate`
}

/**
 * @summary Takes a party out of new selections.
 */
export const deactivateParty = async (partyId: string, options?: Parameters<typeof apiClient>[1]): Promise<PartyDetails> => {

  return apiClient<PartyDetails>(getDeactivatePartyUrl(partyId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDeactivatePartyMutationKey = () => ['deactivateParty'] as const;

export const getDeactivatePartyMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateParty>>, TError,DeactivatePartyMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deactivateParty>>, TError,DeactivatePartyMutationVariables, TContext> => {

const mutationKey = getDeactivatePartyMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivateParty>>, DeactivatePartyMutationVariables> = (props) => {
          const {partyId} = props ?? {};

          return  deactivateParty(partyId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivatePartyMutationResult = NonNullable<Awaited<ReturnType<typeof deactivateParty>>>

    export type DeactivatePartyMutationError = ApiProblem
    export type DeactivatePartyMutationVariables = {partyId: string}

    /**
 * @summary Takes a party out of new selections.
 */
export const useDeactivateParty = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateParty>>, TError,DeactivatePartyMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivateParty>>,
        TError,
        DeactivatePartyMutationVariables,
        TContext
      > => {
      return useMutation(getDeactivatePartyMutationOptions(options), queryClient);
    }
    export const getActivatePartyUrl = (partyId: string,) => {




  return `/api/v1/parties/${partyId}/activate`
}

/**
 * @summary Activates a deactivated party again.
 */
export const activateParty = async (partyId: string, options?: Parameters<typeof apiClient>[1]): Promise<PartyDetails> => {

  return apiClient<PartyDetails>(getActivatePartyUrl(partyId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getActivatePartyMutationKey = () => ['activateParty'] as const;

export const getActivatePartyMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateParty>>, TError,ActivatePartyMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof activateParty>>, TError,ActivatePartyMutationVariables, TContext> => {

const mutationKey = getActivatePartyMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateParty>>, ActivatePartyMutationVariables> = (props) => {
          const {partyId} = props ?? {};

          return  activateParty(partyId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivatePartyMutationResult = NonNullable<Awaited<ReturnType<typeof activateParty>>>

    export type ActivatePartyMutationError = ApiProblem
    export type ActivatePartyMutationVariables = {partyId: string}

    /**
 * @summary Activates a deactivated party again.
 */
export const useActivateParty = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateParty>>, TError,ActivatePartyMutationVariables, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateParty>>,
        TError,
        ActivatePartyMutationVariables,
        TContext
      > => {
      return useMutation(getActivatePartyMutationOptions(options), queryClient);
    }
